# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTRnUdm4c5Z8Ftg2iBCKOZWC2foUFZGI
"""

import streamlit as st
import datetime

st.set_page_config(layout="wide")
st.title('Test Streamlit')

result1 = st.button("click me1!")
if result1:
    st.write('you click on 1')

result2 = st.button("click me2!", type="tertiary")
if result1 & result2:
    st.write('you click both')

st.button("Reset", type="primary")