# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTRnUdm4c5Z8Ftg2iBCKOZWC2foUFZGI
"""

import streamlit as st
import random

st.title('Test Streamlit')
st.write('Hello Guest!')

if st.button('Generate Random Number'):
    random_number = random.randint(1, 100)
    st.write(f'Random Number: {random_number}')